## Example config file.

# The bot's token.
bot_token: mfa.syfydwefbvwet

# The bots.discord.pw token.
dbots_token: dniewudbyuewbdfuewvfueqwh89defbewyfbuewhf

# The cogs to load.
autoload:
  - joku.cogs.debug

# The RethinkDB data.
rethinkdb:
  host: localhost
  port: 28015
  db: jokusoramame

# The redis configuration.
redis:
  address: !!python/tuple ["127.0.0.1", 6432]

# If the bot is in developer mode or not.
# If it is, the bot will be booted in non-sharded mode, beware!
developer_mode: false

# The game text rotation.
game_rotation:
  - "Type j!help for help!"

# Log channel IDs.
log_channels:
  error_channel: 0
